name = "gstdx"
version = "0.1.0"

description = "Extended stdlib for Gleam"
licences = ["Apache-2.0"]
repository = { type = "github", user = "qezz", repo = "gstdx" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
